version: "3"

services:
  app:
    build: ./modules/spotify/.docker/
    container_name: ssmg_app
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./modules/spotify:/home/node/spotify
    entrypoint: ./.docker/entrypoint.sh
    depends_on:
      - rabbitmq
    networks:
      - ssmg-network

  video:
    build: ./modules/video/.docker/
    container_name: ssmg_video
    restart: on-failure
    env_file: .env
    volumes:
      - ./modules/video:/home/python/video
    entrypoint: ./.docker/entrypoint.sh
    depends_on:
      - rabbitmq
    networks:
      - ssmg-network

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: ssmg_rabbitmq
    hostname: rabbitmq
    ports:
      - "${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}"
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    volumes:
      - ./modules/rabbitmq/data:/var/lib/rabbitmq/
      - ./modules/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    env_file: .env
    networks:
      - ssmg-network

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:4510-4559:4510-4559"
      - "127.0.0.1:4566:4566"
    environment:
      - DEFAULT_REGION=sa-east-1
      - DEBUG=${DEBUG-}
      - DATA_DIR=${DATA_DIR-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  ssmg-network:
    driver: bridge
