version: "3"

services:
    app:
        build: ./modules/app
        container_name: ssmg_app
        entrypoint: ./.docker/entrypoint.sh
        restart: always
        ports:
          - ${APP_PORT}:${APP_PORT}
        volumes:
            - ./modules/app:/home/node/app
        env_file:
            .env
        networks:
            - ssmg-networksite

networks:
    ssmg-networksite:
        driver: bridge
    
