version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./.docker/node/Dockerfile
    container_name: 'app'
    env_file: .env
    environment:
      - NODE_ENV=staging
    restart: always
    volumes:
      - ./src:/app
    ports:
      - "5500:5500"
    command: npm start
